### ISSUE TITLE
bug: process should come with "organization" field attached

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#107]
**Describe the bug**
When retrieving a process via the API, part of the response is the ID of the organization creating such process, but there's no way to access the organization right now from the SDK classes.

**Current behavior**
Organization id comes with the request, but it's not mapped to the election class

**Expected behavior**
To be able to access `process.organizationId` or something similar to get that value.

**Comment by marcvelmer** [comment]
Fixed in #110
