### ISSUE TITLE
Add metadata info into the Account object

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/vocdoni-sdk#135]
Right now the SDK returns the "AccountData" object with the "infoURL" as a string on it. 

The SDK should retrieve the info in this URL and if any metadata is available, return it as an array of "key:value" inside the "metadata" field. 

Current behavior: 
```
type AccountData = {
...
infoURL?: string;
}
```

Expected behavior:
```
type AccountData = {
...
metadata: Account; // object with IPFS data in key->value pairs
}
```

**Comment by marcvelmer** [comment]
Fixed in #149
