### ISSUE TITLE
bug: setAccountInfo tries to create an existing account, crashing on the attempt

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#139]
**Describe the bug**
When trying to update an account via setAccountInfo it tries to re-create it rather than update it, crashing on the attempt

**To Reproduce**

- Use `createAccount` to ensure your account is created
- Use `setAccountInfo` trying to update any field (name, description.. doesn't matter)
- You'll get the error `vochain replied with error code: (1) checkTx createAccountTx: account already exists`

**Current behavior**
It crashes with the error `vochain replied with error code: (1) checkTx createAccountTx: account already exists`

**Expected behavior**
To be able to update the account data.

**System:**

- SDK Version 0.0.8

**Comment by marcvelmer** [comment]
Fixed in #149
