### ISSUE TITLE
bug: wrong mapping for account media fields

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#145]
### Describe the bug
Organizations/accounts have a `media` field containing `logo`, `avatar` and `header` images. The SDK maps these directly to the `Account` class, so they should be accessible via `account.logo`, `account.avatar`, etc.

There's something wrongly mapped, since using `account.whatever` is not working, but using "unexistent class keys", like `account.media.logo` works. Note that, to do this using typescript, you must enforce the type to be as `any`, because there's no equivalent having the `media` fields being exported.

### To Reproduce
- Create an account with media fields specified.
- Fetch it via `fetchAccountInfo`
- Try to access any of the images using the account instance.

### Current behavior
All media fields are accessible via the (non-existent) `account.media` field.

### Expected behavior
To be able to retrieve all media using the declared Account properties.

**Comment by marcvelmer** [comment]
Is this fixed in #154 @elboletaire ?

**Comment by marcvelmer** [comment]
Should be tested in: https://github.com/vocdoni/vocdoni-sdk/blob/main/test/integration/account.test.ts#L75
