### ISSUE TITLE
feature: Unify how Account/Org request and response objects are treated.

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#150]
### Describe the feature
Right now, when we create an account, we have a `Account` class with all the required fields unified in one level, meaning we create accounts this way:
~~~ts
new Account({
  name: 'John Doe',
  description: 'A description about this account',
  avatar: 'https://whatever-avatar.png'
})
~~~
But, when getting an account info, the response object looks like...
~~~ts
{
  address: '0x000...',
  balance: 0,
  metadata: {
    media: {
      avatar: 'https://whatever-avatar.png',
    },
  },
}
~~~
Meaning we need to use `account.metadata.media.avatar` to access something that, using `Account` class is just `account.avatar`.

### Motivation
This does not happen in processes :)

### Proposal
Return `Account` instance from account info responses, which has the metadata fields integrated in a single level, rather than the current IAccount with metadata fields split into different levels.

### Components affected
I think only Organization, but maybe could be a good moment to check Process and ensure there's unified too.

**Comment by marcvelmer** [comment]
Fixed in #154
