### ISSUE TITLE
feature: create-react-app is abandoned. Remove its example to avoid confussion

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#260]
### Describe the feature
We're still maintaining a create-react-app when it is abandoned since a year ago. Having that example here may lead to confusion, and give us more troubles than anything.

### Motivation
Users asked in support about issues with create-react-app that are expected, since it's abandoned. See https://github.com/facebook/create-react-app/issues/13140

### Proposal
Remove cra example (we have the vite one which is a copy from cra, and just works better).

### Components affected
Examples

**Comment by marcvelmer** [comment]
Done. Now Vite is deployed.
