### ISSUE TITLE
feature: Update links to the explorer

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#404]
### Describe the feature
With the complete revamp of the explorer, all routes receiving params have been changed. We should update any explorer links in the explorer and its docs to properly point to the new ones. 

> [!NOTE]
> Even though the SDK code itself may not have links pointing there, we have lots of examples and documentation where we might be pointing to the old urls.

See https://github.com/vocdoni/ui-scaffold/issues/740 for a full list of the routes that have potentially changed.

Note [the explorer will have support for old routes](https://github.com/vocdoni/explorer/pull/84), so this won't be required immediately, but it would be good to do it as soon as the LTS explorer has been finally deployed (see https://github.com/vocdoni/explorer/pull/81 for a follow-up on this).

**Comment by marcvelmer** [comment]
URLs are the same, there are no routes in the SDK

**Comment by elboletaire** [comment]
This was to review all readme and examples (I should be more clear, sorry for that), I see some links in the examples... 

https://github.com/vocdoni/vocdoni-sdk/blob/main/examples/tutorial/src/vote.ts#L13
