### ISSUE TITLE
feature: add cumulative voting type

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-sdk#408]
### Describe the feature
Like quadratic voting, but with `costExponent=1`.

### Motivation
Being able to properly identify votings of this type. You have an example voting of this type here: https://explorer.vote/process/6b342d99f2187bf87ae56dfceaf3b6531c336365830e460e212d02000000006d

### Constraints & Assumptions
Not sure it can be detected easily since we are not storing any metadata for these kind of votings and maybe we should, but that would not make old votings to be available after release. Due to this, it may be a better solution to simply identify it based on the params it already has defined (?).

**Comment by marcvelmer** [comment]
It's already been there, it's the budget election type.

Quadratic voting has been added in #410 .

**Comment by elboletaire** [comment]
> It's already been there, it's the budget election type.
> 
> Quadratic voting has been added in #410 .

Wait, then what was the quadratic example we had in the SDK? 🤔 https://github.com/vocdoni/vocdoni-sdk/blob/main/examples/typescript/src/quadratic.ts
