### ISSUE TITLE
bug: use local vocone in CI, instead of remote API

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-sdk#6]
if i understand the issue correctly:
the CI is currently hitting a realworld API (`secrets.API_URL`)
https://github.com/vocdoni/vocdoni-sdk/blob/088ced66cc98ffcf98bdc0424a6495318662918f/.github/workflows/main.yml#L34-L37
while it should spin up a ephemeral vochain using vocone on docker, and hit that instead.

**Comment by marcvelmer** [comment]
Already done at 0c173743749a78cc34b4adae86cc7f4efc4298b9
