### ISSUE TITLE
feature: Define and export process status types

### ISSUE THREAD

**Issue by emmdim** [vocdoni/vocdoni-sdk#93]
**Motivation**
Most applications need a  VotingStatus  in order to evaluate wether a user can vote or other similar cases.

**Describe the feature**
Define and export a Voting Status type  that would contain at least the following states:
>  Upcoming,  Active,  Paused,  Ended,  Canceled
and would be calculated as a combination of the  process status from the API and the params like blockNumber, startTime, endTime

**Proposal**
Implement similar to:
https://github.com/vocdoni/explorer-ui/blob/master/lib/util.ts#L61-L100
https://github.com/vocdoni/vocdoni-ui/blob/main/lib/util.ts#L89

**Comment by marcvelmer** [comment]
Fixed in #113
